### ISSUE TITLE
Lotka-Volterra test segfaults with sufficient time

### ISSUE THREAD

**Issue by chipbuster** [clauswilke/pinetree#1]
## To Reproduce

 - Compile as normal
 - Change runtime in `tests/params/lotka_voltera.yml` to some large number (I have found >600 consistently works)
 - Run pinetree

This should segfault the library.

## Cause

I've traced the segfault to `pinetree/simulation.cpp` on line 219. The following is the relevant snippet:

```
  auto next_reaction = Random::WeightedChoiceIndex(reactions_, alpha_list_);
  reactions_[next_reaction]->Execute();    // SEGFAULT HERE
  UpdatePropensity(next_reaction);
  iteration_++;
```

It seems the WeightedChoiceIndex is somehow choosing elements off the end of the list. Adding an `assert(next_reaction < reactions_.size())` before this line will trigger the assertion.

**Comment by benjaminjack** [comment]
The segfault occurs because the pinetree tries to execute a reaction when all reaction propensities are 0 (i.e. there are no more reactants left). This seems like a rounding error when updating the cached `alpha_sum_`. Previously, there was a check only to see if `alpha_sum_ == 0`. In the lotka voltera simulation, `alpha_sum_` eventually drops to slightly less than 0 (~4E-10), then pinetree segfaults. As a temporary fix, pinetree will now throw an error when `alpha_sum_ <= 0` (cf7fa60d00373622df7e1d191aef7e3da1231ee8). I need to eventually find a more user-friendly way of handling this.
